### ISSUE TITLE
Add information on legal requirements need for contributions

### ISSUE THREAD

**Issue by platipodium** [opengeos/HyperCoast#110]
### Description

As part of the review for JOSS at https://github.com/openjournals/joss-reviews/issues/7025 we are asked whether the community information is complete.  

The project gives useful and elaborate information on How to Contribute in its `contributing.md` file as part of the documentation and source. 

### Missing information

The legal aspects of a third-party contributions are missing.  Do you need copyright transfer?  Do you have a contributor license agreement?  This is as of yet a much neglected (but legally required) aspect of Open Source collaborative development, please add statements to guide your potential contributors to clarify the copyright of their contributions to your project. 

You may have a look at the Harmony Agreements for more explanations and potential solutions. See https://www.harmonyagreements.org

**Comment by giswqs** [comment]
Thank you for the suggestion. Do you have recommendations for sample repositories that use Harmony Agreements?

**Comment by giswqs** [comment]
What do you think about this Contributor License Agreement (CLA) assistant?
https://github.com/cla-assistant/cla-assistant

**Comment by platipodium** [comment]
https://contributoragreements.org/ seems also useful, though I have not used it yet for production.  It seems to be very much in line with what harmony agreements suggest.  What it adds is the link to institutional license policies (if they are publicly accessible)

**Comment by platipodium** [comment]
> Do you have recommendations for sample repositories that use Harmony Agreements?

Actually I don't.  In our latest repo we have the individual CLA built from the Harmony Agreements https://codebase.helmholtz.cloud/mussel/netlogo-northsea-species/-/blob/main/doc/contributing/contributing-license.md, but we have not yet had to apply it, as the contribution legal issues with the current contributor team in this (and other research projects I run) are dealt with  by separate inter-institutional memoranda.

**Comment by giswqs** [comment]
@platipodium Can you take a look at #111 to see if it address your comments?

**Comment by platipodium** [comment]
OK, great, that certainly addresses the individual CLA.  

* How would you deal with entity CLAs?  
* Have you tested the CLA GitHub workflow?

**Comment by platipodium** [comment]
Also link the CLA in your contributing.md

**Comment by giswqs** [comment]
The entity CLA has been added and the links to the CLAs have been added to contributing.md. 

The CLA GitHub workflow will be tested once this PR has been merged. Will fix it if it is not working properly.

**Comment by giswqs** [comment]
I installed CLA assistant to the repo through https://cla-assistant.io. You can see from my pull request that the CLA assistant is working properly now. 
https://github.com/opengeos/HyperCoast/pull/112#issuecomment-2282898038
