### ISSUE TITLE
Address JOSS review comments

### ISSUE THREAD

**Issue by giswqs** [opengeos/HyperCoast#117]
I will be using this issue to address the JOSS review comments by @alexgleith in https://github.com/openjournals/joss-reviews/issues/7025#issuecomment-2297757431

PRs will be created to address each comments if needed. 

--------------------------------------------------------------------
Some very minor comments on code quality:

- There are some unused imports, like numpy in desis.py and others that are probably imported for the context function (not the right word), but should be annotated, like import hvplot.xarray  # noqa F401. These are little, but my linter highlights them, and it's cleaner to fix it.
- In the main hypercoast.py file, there are * imports, which are not recommended from .aviris import *
- spectral is used, but isn't in the dependencies list
- I'll make a PR with some example code cleanups.

Some opinions from me:

- I don't like that EMIT data has been stored in GitHub, like this: https://github.com/opengeos/datasets/releases/tag/netcdf. I would much prefer that the notebooks point to the data direct at NASA.
- Following on from the first point, wrapping up the EarthData access into the download_nasa_data function, which calls leafmap.nasa_data_download, which then calls earthaccess.download is two abstractions too far! It does make it simple, though. I have an [example over here](https://github.com/auspatious/hyperspectral-notebooks/blob/main/00_EMIT_STAC_Search.ipynb) that uses NASA's STAC API to find EMIT granules and load them, and it's still pretty complex, but what is good is that it uses the open standard STAC to discover granules.
- It's great that the function emit_xarray has been adapted to make wavelength a dimension!
- I can't see how this method, in the emit.ipynb notebook is working, or if it works. I tried changing the numbers and nothing changed: m.add("spectral", xlim=(400, 1400))
- The function m.spectral_to_df() structures the dataframe in an unexpected way. I think exporting something with a geometry, or with lon/lat columns and 285 more spectral columns would make more sense, even if the structure is a bit clumsy.

On the review points, I'd like a couple of changes please:

1. ~~For installation, please make sure all dependencies are listed in the pyproject.toml file (spectral was not, and neither was pyvista).~~ Edit: resolved by removing unused code.
2. ~~For community guidelines, please include a [contributing file](https://github.com/opendatacube/datacube-core/blob/develop/CONTRIBUTING.md)~~. Edit: my mistake, there's a contributing file in the docs folder.

**Comment by giswqs** [comment]
> I don't like that EMIT data has been stored in GitHub, like this: https://github.com/opengeos/datasets/releases/tag/netcdf. I would much prefer that the notebooks point to the data direct at NASA.

The purpose of those three sample files was to make the GitHub Actions unit tests run faster. It takes ~30 seconds to download the sample data, a bit faster than downloading using earthaccess. As we have many notebook examples that use EMIT and PACE data, I try to avoid using my personal NASA EarthData account for authentication to repeatedly downloading these datasets for every commits in a PR. 

Additionally, the sample data lowers the barriers for users to try out the HyperCoast features. Users can launch the notebook on Google Colab and explore the functionality without having to sign up for a NASA EarthData account and authenticate it in the notebook. We do provide a separate notebook example ([search_data.ipynb](https://hypercoast.org/examples/search_data/))  that demonstrates how to download NASA EarthData interactively and programmatically.

@alexgleith   Would these arguments be acceptable to you?

![image](https://github.com/user-attachments/assets/50c0e211-ff51-4b0c-bb6e-f54a6ebe1e79)

**Comment by giswqs** [comment]
> I can't see how this method, in the emit.ipynb notebook is working, or if it works. I tried changing the numbers and nothing changed: m.add("spectral", xlim=(400, 1400))

The `xlim` parameter is used to limit the wavelength range to be displayed on the plot. It works as expected on my end. 

## Without xlim
```python
m = hypercoast.Map()
m.add_basemap("SATELLITE")
m.add_emit(dataset, wavelengths=[1000, 600, 500], vmin=0, vmax=0.3, layer_name="EMIT")
m.add("spectral")
m
```
![image](https://github.com/user-attachments/assets/c40be2a2-50f4-4b7a-8e3a-1c430ede5058)

## With xlim
```python
m = hypercoast.Map()
m.add_basemap("SATELLITE")
m.add_emit(dataset, wavelengths=[1000, 600, 500], vmin=0, vmax=0.3, layer_name="EMIT")
m.add("spectral", xlim=(400, 1200))
m
```
![image](https://github.com/user-attachments/assets/7132cb6c-fb47-4de9-8e5b-a970b3992318)

**Comment by alexgleith** [comment]
> wavelength range to be displayed on the plot

Ah, on the plot! I was expecting it to stretch on the map. Now it makes sense that it's `xlim` and not `zlim` for the actual visualisation.

**Comment by giswqs** [comment]
> The function m.spectral_to_df() structures the dataframe in an unexpected way. I think exporting something with a geometry, or with lon/lat columns and 285 more spectral columns would make more sense, even if the structure is a bit clumsy.

The strcture of the dataframe looks like this. It is easier to plot a data strucutre like this with [bqplot](https://bqplot.github.io/bqplot/) (the libary we use for plotting spectral profiles), which takes a dataframe with x and y columns. 

However, I do like your suggestion for export something with a geometry. I will create a `spectral_to_gdf` method for exporting a geodataframe. One caveat is that the shapefile format generally does not like >256 columns. Anyway, we can let users decide what vector data format they want to convert the GeoDataFrame to. 

![image](https://github.com/user-attachments/assets/e8c1616f-7609-4f59-8c71-76ae3878fa42)

**Comment by alexgleith** [comment]
>The purpose of those three sample files was to make the GitHub Actions unit tests run faster.

This makes sense.

>We do provide a separate notebook example ([search_data.ipynb](https://hypercoast.org/examples/search_data/)) that demonstrates how to download NASA EarthData interactively and programmatically.

It _does_, but it also wraps the earthdata functions in a leafmap function that is used by the separate hypercoast function. I'm not really sure why it does this, and it obfuscates the way that the underlying earthdata API, and Python libraries work.

**Comment by alexgleith** [comment]
> I will create a spectral_to_gdf method for exporting a geodataframe.

Good idea!

> the shapefile format generally does not like >256 columns

Hmm, yeah, a bit of an issue, but it's nice to have an excuse to not support Shapefiles! haha

**Comment by giswqs** [comment]
The `Map.spectral_to_gdf()` method has been added in https://github.com/opengeos/HyperCoast/pull/118

**Comment by giswqs** [comment]
> It does, but it also wraps the earthdata functions in a leafmap function that is used by the separate hypercoast function. I'm not really sure why it does this, and it obfuscates the way that the underlying earthdata API, and Python libraries work.

The `leafmap.nasa_data_search()` function wraps the `earthaccess.search_data()` method with additional inprovements, such as returning the data footprints as a GeoDataFrame, or saving it as a vector format (e.g., geojson, shapefile).
https://github.com/opengeos/leafmap/blob/a6dae078146064a870fa2aada5d462259651e3bc/leafmap/common.py#L13296

The reason that hypercoast wraps the leafmap functions is to simplify the import statements in the notebook examples. Most notebook examples only need `import hypercoast` so that users don't need to learn other dependencies.

**Comment by giswqs** [comment]
@alexgleith I have fixed the linter warnings in https://github.com/opengeos/HyperCoast/pull/128. Thank you once again for taking the time to review it and providing constructive feedback.

**Comment by alexgleith** [comment]
>Thank you once again for taking the time to review it

You're very welcome, @giswqs. Thank you for being receptive to the feedback!
