### ISSUE TITLE
Clarify authorship

### ISSUE THREAD

**Issue by platipodium** [opengeos/HyperCoast#119]
This is part of the review at https://github.com/openjournals/joss-reviews/issues/7025

- In your paper, you state Wu & Liu as authors.   No-one else is acknowledged
- In your git history, there are small contributions by Leith, Slowy & Ponce-Campos

Please clarify.  You might have a look at [all contributors ](https://allcontributors.org).

**Comment by giswqs** [comment]
Thank you for the suggestion. This issue has been addressed in #120 and #121
