### ISSUE TITLE
variable chlor_a not found

### ISSUE THREAD

**Issue by smcclatchie** [opengeos/HyperCoast#148]
### Environment Information

-   hypercoast version: hypercoast                0.10.0
-   Python version: Python 3.11.6
-   Operating System: Ubuntu 24.04 LTS

### Description

I was trying to read a PACE chlorophyll file using:
array = hc.read_pace_chla("/mnt/data/dynamic_data/projects/projects2022/recreational_fishing_Chlorophyll/data/regional_downloads/PACE_OCI.20241208T025344.L2.OC_BGC.V2_0.NRT.nc")
 
and received an error:
KeyError: "No variable named 'chlor_a'. Variables on the dataset include ['date']"

### What I Did

I simplified the problem and tested the read_pace_chla function on the command line as follows:

(base) smcclatchie@Jaguar:/mnt/data/dynamic_data/projects/projects2022/recreational_fishing_Chlorophyll/data/regional_downloads$ conda activate hyper
(hyper) smcclatchie@Jaguar:/mnt/data/dynamic_data/projects/projects2022/recreational_fishing_Chlorophyll/data/regional_downloads$

(hyper) smcclatchie@Jaguar:/mnt/data/dynamic_data/projects/projects2022/recreational_fishing_Chlorophyll/data/regional_downloads$ python
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hypercoast as hc
>>> 

>>> import os
>>> os.system('ls -al')
total 17664
drwxrwxr-x 2 smcclatchie smcclatchie     4096 Dec 19 13:05 .
drwxrwxr-x 3 smcclatchie smcclatchie     4096 Dec 18 21:11 ..
-rw-rw-r-- 1 smcclatchie smcclatchie 18079178 Dec 19 13:05 PACE_OCI.20241208T025344.L2.OC_BGC.V2_0.NRT.nc
0
>>> 

chla_data = hc.read_pace_chla('./PACE_OCI.20241208T025344.L2.OC_BGC.V2_0.NRT.nc')

Traceback (most recent call last):
  File "/home/smcclatchie/anaconda3/envs/hyper/lib/python3.11/site-packages/xarray/core/dataset.py", line 1511, in _construct_dataarray
    variable = self._variables[name]
               ~~~~~~~~~~~~~~~^^^^^^
KeyError: 'chlor_a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smcclatchie/anaconda3/envs/hyper/lib/python3.11/site-packages/xarray/core/dataset.py", line 1610, in __getitem__
    return self._construct_dataarray(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smcclatchie/anaconda3/envs/hyper/lib/python3.11/site-packages/xarray/core/dataset.py", line 1513, in _construct_dataarray
    _, name, variable = _get_virtual_variable(self._variables, name, self.sizes)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smcclatchie/anaconda3/envs/hyper/lib/python3.11/site-packages/xarray/core/dataset.py", line 220, in _get_virtual_variable
    raise KeyError(key)
KeyError: 'chlor_a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smcclatchie/anaconda3/envs/hyper/lib/python3.11/site-packages/hypercoast/pace.py", line 182, in read_pace_chla
    chla = np.log10(dataset["chlor_a"])
                    ~~~~~~~^^^^^^^^^^^
  File "/home/smcclatchie/anaconda3/envs/hyper/lib/python3.11/site-packages/xarray/core/dataset.py", line 1616, in __getitem__
    raise KeyError(message) from e
KeyError: "No variable named 'chlor_a'. Variables on the dataset include ['date']"
>>> 

I checked the netcdf file with ncview. The chlor_a variable is in the geophysical group as expected. I'm wondering if there is a bug where the function is not opening the group to acquire the variable, so it is report it as missing.

**Comment by giswqs** [comment]
That function is for reading Level-3 data.

First reading Level-2 data, follow this example: https://hypercoast.org/examples/pace_oci_l2/

Feel free to reopen the issue if it still doesn't work
