### ISSUE TITLE
Files that cross the antimeridian don't render correctly

### ISSUE THREAD

**Issue by jessjaco** [opengeos/HyperCoast#30]
A file from e.g. [this search](https://search.earthdata.nasa.gov/search/granules?portal=obdaac&p=C2910373786-OB_CLOUD&pg[0][v]=f&pg[0][gsk]=-start_date&g=G2990640292-OB_CLOUD&q=PACE&sb[0]=177.0249%2C-18.40446%2C178.73438%2C-17.24009&tl=1715356457.772!3!!&lat=-8.625835&zoom=1) which crosses the antimeridian doesn't render correctly

```python
import hypercoast
pace_file = "./PACE_OCI.20240510T003914.L2.OC_AOP.V1_0_0.NRT.nc"
dataset = hypercoast.read_pace(pace_file)
hypercoast.viz_pace(dataset, wavelengths=[500, 510, 520, 530], ncols=2)
```

produces
![image](https://github.com/opengeos/HyperCoast/assets/1250693/b409b125-3ec3-4ab1-8149-072cf2ec7ecc)

**Comment by giswqs** [comment]
Thank you for reporting this bug. I can reproduce the issue. It seems to be an issue with xarray and matplotlib. 

```python
dataset = hypercoast.read_pace(filepath)
data = dataset.sel(wavelength=500)['Rrs']
data.plot(cmap="jet", vmin=0, vmax=0.02)
```
![image](https://github.com/opengeos/HyperCoast/assets/5016453/361010a7-fce8-4e3d-8bd1-345bcd7191c8)

The image can be displayed on the interactive map properly. 
![image](https://github.com/opengeos/HyperCoast/assets/5016453/1af3df17-3e30-48e4-bce2-cb84c8ffa7be)

**Comment by giswqs** [comment]
Relevant question: https://gis.stackexchange.com/questions/205871/xarray-slicing-across-the-antimeridian
It appears to be an xarray issue. I would suggest reporting it on the [xarray repo](https://github.com/pydata/xarray).

**Comment by jessjaco** [comment]
Very well.
